import type { DB, Permission, Role } from "./types";

const MODULES = [
  "Branches",
  "Customers",
  "Projects",
  "Products",
  "Quotations",
  "Inspections",
  "Documents",
  "FollowUps",
  "Reports",
  "Users",
  "Roles",
  "Settings",
] as const;

const fullPerms = (): Permission[] => MODULES.map((m) => ({ module: m, view: true, create: true, update: true, delete: true }));

const staffPerms = (): Permission[] =>
  MODULES.map((m) => ({
    module: m,
    view: true,
    create: ["Customers", "Projects", "Quotations", "Inspections", "Documents", "FollowUps"].includes(m),
    update: ["Customers", "Projects", "Quotations", "Inspections", "Documents", "FollowUps"].includes(m),
    delete: false,
  }));

const seedRoles: Role[] = [
  { id: 1, name: "Super Admin", isAdmin: true, level: 0, permissions: fullPerms() },
  { id: 2, name: "System Admin", isAdmin: true, level: 0, permissions: fullPerms() },
  { id: 3, name: "Branch Staff", isAdmin: false, level: 1, permissions: staffPerms() },
  { id: 4, name: "Branch Admin", isAdmin: true, level: 1, permissions: fullPerms() },
  { id: 5, name: "Architect", isAdmin: false, level: 2, permissions: staffPerms() },
  { id: 6, name: "Interior Designer", isAdmin: false, level: 2, permissions: staffPerms() },
];

export const seed: DB = {
  branches: [
    { id: 1, code: "AHM", name: "Ahmedabad", address: "Corporate House, SG Highway, Ahmedabad", city: "Ahmedabad", gst: "24AAECA0000A1Z5", contact: "98765 43210 · ahm@artelier.example", status: "Active" },
    { id: 2, code: "MUM", name: "Mumbai", address: "Trade Tower, Andheri East, Mumbai", city: "Mumbai", gst: "27AAECA0000A1Z5", contact: "98200 12345 · mumbai@artelier.example", status: "Active" },
    { id: 3, code: "SUR", name: "Surat", address: "Orbit Complex, Adajan, Surat", city: "Surat", gst: "24AAECA0000A2Z4", contact: "99090 12345 · surat@artelier.example", status: "Active" },
  ],
  customers: [
    { id: 1, code: "C-1001", name: "Rajesh Patel", company: "Orion Manufacturing", mobile: "9876543210", email: "projects@orion.example", address: "Survey No. 45, Sanand Road", city: "Ahmedabad", gst: "24AAACO1234A1Z5", branches: ["Ahmedabad"], source: "Direct Client" },
    { id: 2, code: "C-1002", name: "Priya Sharma", company: "Aster Interiors", mobile: "9825012345", email: "studio@aster.example", address: "201, Sunrise Complex, Bodakdev", city: "Ahmedabad", gst: "24AAACA5678B1Z2", branches: ["Ahmedabad"], source: "Interior Designer" },
    { id: 3, code: "C-1003", name: "Amit Singh", company: "Vertex Industries", mobile: "9810012345", email: "procurement@vertex.example", address: "Plot 12, MIDC Andheri", city: "Mumbai", gst: "27AAACV9012C1Z3", branches: ["Mumbai"], source: "Builder" },
    { id: 4, code: "C-1004", name: "Kavya Desai", company: "Nova Engineering", mobile: "9909012345", email: "admin@nova.example", address: "45, GIDC Estate, Sachin", city: "Surat", gst: "24AAACN3456D1Z4", branches: ["Surat"], source: "Architect" },
  ],
projects: [
    { id: 1, code: "PRJ-101", name: "Corporate Office", customer: "C-1001", type: "Commercial", stage: "Execution", status: "Active", expected: "2026-10-15", siteAddress: "Corporate Office, SG Highway", siteCity: "Ahmedabad", siteState: "Gujarat", sitePincode: "380054", billingAddress: "Orion Manufacturing, SG Highway", billingCity: "Ahmedabad", billingState: "Gujarat", billingPincode: "380054", surfaces: [{ id: 1, category: "Micro Cement", finish: "Smooth", shade: "Stone", area: 1250, thickness: "2 mm", rate: 185 }, { id: 2, category: "Liquid Metal", finish: "Metallic", shade: "Silver", area: 480, thickness: "2 mm", rate: 260 }, { id: 3, category: "Stone Finish", finish: "Stone", shade: "Slate", area: 620, thickness: "3 mm", rate: 220 }], photos: [], branches: ["Ahmedabad"], history: [{ id: 1, date: "2026-08-01", stage: "Design", status: "Active", note: "Project initiated", user: "Super Admin" }] },
    { id: 2, code: "PRJ-102", name: "Lakeview Villa", customer: "C-1002", type: "Residential", stage: "Design", status: "Active", expected: "2027-01-30", siteAddress: "Lakeview Villa, Bodakdev", siteCity: "Ahmedabad", siteState: "Gujarat", sitePincode: "380054", billingAddress: "Aster Interiors, Bodakdev", billingCity: "Ahmedabad", billingState: "Gujarat", billingPincode: "380054", surfaces: [{ id: 1, category: "Stucco", finish: "Trowel", shade: "Cream", area: 2100, thickness: "2 mm", rate: 175 }, { id: 2, category: "Rammed Earth", finish: "Earth", shade: "Ochre", area: 850, thickness: "5 mm", rate: 205 }], photos: [], branches: ["Ahmedabad"], history: [{ id: 1, date: "2026-07-15", stage: "Design", status: "Active", note: "Initial design phase", user: "Branch Admin" }] },
    { id: 3, code: "PRJ-103", name: "Factory Reception", customer: "C-1003", type: "Commercial", stage: "Execution", status: "Active", expected: "2026-09-20", siteAddress: "MIDC Industrial Area", siteCity: "Mumbai", siteState: "Maharashtra", sitePincode: "400093", billingAddress: "Vertex Industries, MIDC", billingCity: "Mumbai", billingState: "Maharashtra", billingPincode: "400093", surfaces: [{ id: 1, category: "Decorative Paint", finish: "Brush", shade: "Sage", area: 1400, thickness: "1 mm", rate: 160 }, { id: 2, category: "Micro Concrete", finish: "Smooth", shade: "Grey", area: 900, thickness: "2 mm", rate: 195 }], photos: [], branches: ["Mumbai"], history: [{ id: 1, date: "2026-08-01", stage: "Design", status: "Active", note: "Project started", user: "Branch Admin" }, { id: 2, date: "2026-08-10", stage: "Execution", status: "Active", note: "Construction commenced", user: "Branch Admin" }] },
    { id: 4, code: "PRJ-104", name: "Hospitality Lounge", customer: "C-1004", type: "Hospitality", stage: "Completed", status: "Completed", expected: "2026-08-01", siteAddress: "Dumas Road, Surat", siteCity: "Surat", siteState: "Gujarat", sitePincode: "395007", billingAddress: "Nova Engineering, Dumas Road", billingCity: "Surat", billingState: "Gujarat", billingPincode: "395007", surfaces: [{ id: 1, category: "Luxury Texture", finish: "Sculpted", shade: "Linen", area: 1650, thickness: "2 mm", rate: 230 }, { id: 2, category: "Metallic Finish", finish: "Metallic", shade: "Bronze", area: 540, thickness: "2 mm", rate: 240 }, { id: 3, category: "Custom Finishes", finish: "Custom", shade: "By client spec", area: 300, thickness: "2 mm", rate: 250 }], photos: [], branches: ["Surat"], history: [{ id: 1, date: "2026-06-01", stage: "Design", status: "Active", note: "Project initiated", user: "Branch Admin" }, { id: 2, date: "2026-07-01", stage: "Execution", status: "Active", note: "Work in progress", user: "Branch Admin" }, { id: 3, date: "2026-08-01", stage: "Completed", status: "Completed", note: "Project completed", user: "Branch Admin" }] },
    { id: 5, code: "PRJ-105", name: "Training Centre", customer: "C-1001", type: "Commercial", stage: "Design", status: "Active", expected: "2026-11-12", siteAddress: "Chandkheda, Ahmedabad", siteCity: "Ahmedabad", siteState: "Gujarat", sitePincode: "382424", billingAddress: "Orion Manufacturing, Chandkheda", billingCity: "Ahmedabad", billingState: "Gujarat", billingPincode: "382424", surfaces: [{ id: 1, category: "Micro Cement", finish: "Smooth", shade: "Pearl", area: 980, thickness: "2 mm", rate: 185 }], photos: [], branches: ["Ahmedabad"], history: [{ id: 1, date: "2026-08-10", stage: "Design", status: "Active", note: "Design phase started", user: "Branch Admin" }] },
  ],
  products: [
    { id: 1, code: "P-101", name: "Micro Cement", category: "Micro Concrete", textures: ["Smooth"], finishes: ["Smooth"], shades: ["Stone", "Pearl"], textureImage: "", finishImage: "", shadeImages: [], material: "Cementitious", rateSlabs: [{ finish: "Smooth", thickness: "2 mm", materialRate: 120, labourRate: 42 }, { finish: "Smooth", thickness: "3 mm", materialRate: 165, labourRate: 48 }], optionalItems: ["Primer", "Sealer"], hsn: "3214", gst: 18, wastage: 5, transportationSlabs: [{ distance: "0-50 km", rate: 15 }, { distance: "50-100 km", rate: 25 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "185", user: "System Admin" }] },
    { id: 2, code: "P-102", name: "Metallic Finish", category: "Metallic Finish", textures: ["Metallic"], finishes: ["Metallic"], shades: ["Silver", "Bronze"], textureImage: "", finishImage: "", shadeImages: [], material: "Metallic Pigment", rateSlabs: [{ finish: "Metallic", thickness: "1 mm", materialRate: 180, labourRate: 55 }, { finish: "Metallic", thickness: "2 mm", materialRate: 220, labourRate: 60 }], optionalItems: ["Primer", "Protection Coat"], hsn: "3214", gst: 18, wastage: 6, transportationSlabs: [{ distance: "0-50 km", rate: 15 }, { distance: "50-100 km", rate: 25 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "240", user: "System Admin" }] },
    { id: 3, code: "P-103", name: "Textured Finish", category: "Luxury Texture", textures: ["Sandstone"], finishes: ["Sculpted"], shades: ["Sand", "Clay"], textureImage: "", finishImage: "", shadeImages: [], material: "Textured Aggregate", rateSlabs: [{ finish: "Sculpted", thickness: "3 mm", materialRate: 140, labourRate: 48 }, { finish: "Sculpted", thickness: "5 mm", materialRate: 185, labourRate: 52 }], optionalItems: ["Primer", "Sealer"], hsn: "3214", gst: 18, wastage: 5, transportationSlabs: [{ distance: "0-50 km", rate: 15 }, { distance: "50-100 km", rate: 25 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "210", user: "System Admin" }] },
    { id: 4, code: "P-104", name: "Protective Coating", category: "Decorative Paint", textures: ["Matt"], finishes: ["Matt"], shades: ["Clear"], textureImage: "", finishImage: "", shadeImages: [], material: "Polyurethane", rateSlabs: [{ finish: "Matt", thickness: "1 mm", materialRate: 60, labourRate: 20 }], optionalItems: ["Sealer"], hsn: "3208", gst: 18, wastage: 3, transportationSlabs: [{ distance: "0-50 km", rate: 10 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "95", user: "System Admin" }] },
    { id: 5, code: "P-105", name: "Micro Concrete", category: "Micro Concrete", textures: ["Smooth"], finishes: ["Smooth"], shades: ["Grey", "Pearl"], textureImage: "", finishImage: "", shadeImages: [], material: "Cementitious", rateSlabs: [{ finish: "Smooth", thickness: "2 mm", materialRate: 130, labourRate: 45 }, { finish: "Smooth", thickness: "3 mm", materialRate: 175, labourRate: 50 }], optionalItems: ["Primer", "Waterproofing", "Sealer"], hsn: "3214", gst: 18, wastage: 5, transportationSlabs: [{ distance: "0-50 km", rate: 15 }, { distance: "50-100 km", rate: 25 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "195", user: "System Admin" }] },
    { id: 6, code: "P-106", name: "Liquid Metal", category: "Liquid Metal", textures: ["Metallic"], finishes: ["Metallic"], shades: ["Silver", "Bronze", "Copper"], textureImage: "", finishImage: "", shadeImages: [], material: "Metal Resin", rateSlabs: [{ finish: "Metallic", thickness: "1 mm", materialRate: 190, labourRate: 60 }, { finish: "Metallic", thickness: "2 mm", materialRate: 240, labourRate: 70 }], optionalItems: ["Primer", "Protection Coat", "Liquid Metal Inlay"], hsn: "3214", gst: 18, wastage: 6, transportationSlabs: [{ distance: "0-50 km", rate: 20 }, { distance: "50-100 km", rate: 35 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "260", user: "System Admin" }] },
    { id: 7, code: "P-107", name: "Luxury Texture", category: "Luxury Texture", textures: ["Sculpted"], finishes: ["Sculpted"], shades: ["Linen", "Silk"], textureImage: "", finishImage: "", shadeImages: [], material: "Decorative Plaster", rateSlabs: [{ finish: "Sculpted", thickness: "2 mm", materialRate: 150, labourRate: 52 }, { finish: "Sculpted", thickness: "3 mm", materialRate: 200, labourRate: 58 }], optionalItems: ["Primer", "Sealer", "Sample Panel"], hsn: "3214", gst: 18, wastage: 5, transportationSlabs: [{ distance: "0-50 km", rate: 15 }, { distance: "50-100 km", rate: 25 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "230", user: "System Admin" }] },
    { id: 8, code: "P-108", name: "Stucco", category: "Stucco", textures: ["Trowel"], finishes: ["Trowel"], shades: ["Cream", "Terracotta"], textureImage: "", finishImage: "", shadeImages: [], material: "Lime Plaster", rateSlabs: [{ finish: "Trowel", thickness: "3 mm", materialRate: 110, labourRate: 40 }, { finish: "Trowel", thickness: "5 mm", materialRate: 150, labourRate: 45 }], optionalItems: ["Primer", "Waterproofing", "Crack Treatment"], hsn: "3214", gst: 18, wastage: 4, transportationSlabs: [{ distance: "0-50 km", rate: 15 }, { distance: "50-100 km", rate: 25 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "175", user: "System Admin" }] },
    { id: 9, code: "P-109", name: "Decorative Paint", category: "Decorative Paint", textures: ["Brush"], finishes: ["Brush"], shades: ["Ivory", "Sage", "Dusty Rose"], textureImage: "", finishImage: "", shadeImages: [], material: "Acrylic Paint", rateSlabs: [{ finish: "Brush", thickness: "1 mm", materialRate: 100, labourRate: 35 }], optionalItems: ["Primer", "Sealer", "Stencil Work"], hsn: "3208", gst: 18, wastage: 4, transportationSlabs: [{ distance: "0-50 km", rate: 10 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "160", user: "System Admin" }] },
    { id: 10, code: "P-110", name: "Stone Finish", category: "Stone Finish", textures: ["Stone"], finishes: ["Stone"], shades: ["Slate", "Limestone"], textureImage: "", finishImage: "", shadeImages: [], material: "Natural Stone", rateSlabs: [{ finish: "Stone", thickness: "3 mm", materialRate: 160, labourRate: 50 }, { finish: "Stone", thickness: "5 mm", materialRate: 210, labourRate: 55 }], optionalItems: ["Primer", "Sealer", "Protection Coat"], hsn: "3214", gst: 18, wastage: 6, transportationSlabs: [{ distance: "0-50 km", rate: 25 }, { distance: "50-100 km", rate: 40 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "220", user: "System Admin" }] },
    { id: 11, code: "P-111", name: "Rammed Earth", category: "Rammed Earth", textures: ["Earth"], finishes: ["Earth"], shades: ["Sienna", "Ochre"], textureImage: "", finishImage: "", shadeImages: [], material: "Stabilized Earth", rateSlabs: [{ finish: "Earth", thickness: "5 mm", materialRate: 130, labourRate: 47 }, { finish: "Earth", thickness: "10 mm", materialRate: 180, labourRate: 55 }], optionalItems: ["Waterproofing", "Crack Treatment", "Sealer"], hsn: "3214", gst: 18, wastage: 6, transportationSlabs: [{ distance: "0-50 km", rate: 20 }, { distance: "50-100 km", rate: 30 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "205", user: "System Admin" }] },
    { id: 12, code: "P-112", name: "Custom Finish", category: "Custom Finish", textures: ["Custom"], finishes: ["Custom"], shades: ["By client spec"], textureImage: "", finishImage: "", shadeImages: [], material: "Custom", rateSlabs: [{ finish: "Custom", thickness: "Custom", materialRate: 180, labourRate: 55 }], optionalItems: ["Primer", "Sample Panel", "CNC Cut Pattern"], hsn: "3214", gst: 18, wastage: 6, transportationSlabs: [{ distance: "0-50 km", rate: 20 }], history: [{ id: 1, date: "2026-08-01", field: "rate", oldValue: "0", newValue: "250", user: "System Admin" }] },
  ],
  quotations: [
    { id: 1, code: "QT-AHM-26081", customer: "C-1001", project: "PRJ-101", branches: ["Ahmedabad"], surfaceItems: [{ id: 1, productCategory: "Micro Concrete", texture: "Smooth", finish: "Smooth", shade: "Stone", applicationArea: "Wall", area: 1250, thickness: "2 mm", rate: 185, optionalItems: ["Primer", "Sealer"], description: "Micro cement application", remarks: "", materialQuantity: 1313, materialCost: 157560, labourCost: 52500, wastageCost: 7878, transportationCost: 18750, otherCharges: 0, discount: 0, discountType: "percentage", lineTotal: 236688, hsn: "3214", gstRate: 18, gstAmount: 42604 }], optionalItems: [], subtotal: 236688, discount: 0, discountType: "percentage", taxableValue: 236688, gstAmount: 42604, gstRate: 18, amount: 486500, status: "Approved", date: "14 Aug 2026", owner: "Riya Mehta", revision: 2, followUp: "18 Aug 2026", category: "Commercial", placeOfSupply: "Gujarat — CGST + SGST", additionalCharges: 0, roundOff: 0, version: "R2" },
    { id: 2, code: "QT-AHM-26080", customer: "C-1002", project: "PRJ-102", branches: ["Ahmedabad"], surfaceItems: [{ id: 1, productCategory: "Stucco", texture: "Trowel", finish: "Trowel", shade: "Cream", applicationArea: "Wall", area: 2100, thickness: "3 mm", rate: 175, optionalItems: ["Primer", "Waterproofing"], description: "Stucco wall finish", remarks: "", materialQuantity: 2205, materialCost: 242550, labourCost: 84000, wastageCost: 12128, transportationCost: 31500, otherCharges: 0, discount: 0, discountType: "percentage", lineTotal: 370178, hsn: "3214", gstRate: 18, gstAmount: 66632 }], optionalItems: [], subtotal: 370178, discount: 0, discountType: "percentage", taxableValue: 370178, gstAmount: 66632, gstRate: 18, amount: 224800, status: "Under Negotiation", date: "13 Aug 2026", owner: "Karan Desai", revision: 1, followUp: "16 Aug 2026", category: "Residential", placeOfSupply: "Gujarat — CGST + SGST", additionalCharges: 0, roundOff: 0, version: "R1" },
    { id: 3, code: "QT-MUM-26042", customer: "C-1003", project: "PRJ-103", branches: ["Mumbai"], surfaceItems: [{ id: 1, productCategory: "Liquid Metal", texture: "Metallic", finish: "Metallic", shade: "Silver", applicationArea: "Feature Wall", area: 1400, thickness: "1 mm", rate: 260, optionalItems: ["Primer", "Protection Coat"], description: "Liquid metal feature wall", remarks: "", materialQuantity: 1470, materialCost: 279300, labourCost: 84000, wastageCost: 13965, transportationCost: 29400, otherCharges: 0, discount: 0, discountType: "percentage", lineTotal: 406665, hsn: "3214", gstRate: 18, gstAmount: 73200 }], optionalItems: [], subtotal: 406665, discount: 0, discountType: "percentage", taxableValue: 406665, gstAmount: 73200, gstRate: 18, amount: 692300, status: "Sent", date: "12 Aug 2026", owner: "Neel Joshi", revision: 1, followUp: "19 Aug 2026", category: "Commercial", placeOfSupply: "Maharashtra — IGST", additionalCharges: 0, roundOff: 0, version: "R1" },
    { id: 4, code: "QT-SUR-26019", customer: "C-1004", project: "PRJ-104", branches: ["Surat"], surfaceItems: [{ id: 1, productCategory: "Luxury Texture", texture: "Sculpted", finish: "Sculpted", shade: "Linen", applicationArea: "Wall", area: 1650, thickness: "2 mm", rate: 230, optionalItems: ["Primer", "Sample Panel"], description: "Luxury texture finish", remarks: "", materialQuantity: 1733, materialCost: 259950, labourCost: 85800, wastageCost: 12998, transportationCost: 41250, otherCharges: 0, discount: 0, discountType: "percentage", lineTotal: 399998, hsn: "3214", gstRate: 18, gstAmount: 72000 }], optionalItems: [], subtotal: 399998, discount: 0, discountType: "percentage", taxableValue: 399998, gstAmount: 72000, gstRate: 18, amount: 318700, status: "Converted", date: "11 Aug 2026", owner: "Mira Shah", revision: 3, followUp: "—", category: "Hospitality", placeOfSupply: "Gujarat — CGST + SGST", additionalCharges: 0, roundOff: 0, version: "R3" },
    { id: 5, code: "QT-AHM-26077", customer: "C-1001", project: "PRJ-105", branches: ["Ahmedabad"], surfaceItems: [{ id: 1, productCategory: "Micro Concrete", texture: "Smooth", finish: "Smooth", shade: "Pearl", applicationArea: "Floor", area: 980, thickness: "2 mm", rate: 185, optionalItems: ["Primer", "Waterproofing", "Sealer"], description: "Micro concrete flooring", remarks: "", materialQuantity: 1029, materialCost: 123480, labourCost: 44100, wastageCost: 6174, transportationCost: 14700, otherCharges: 0, discount: 0, discountType: "percentage", lineTotal: 188454, hsn: "3214", gstRate: 18, gstAmount: 33922 }], optionalItems: [], subtotal: 188454, discount: 0, discountType: "percentage", taxableValue: 188454, gstAmount: 33922, gstRate: 18, amount: 175400, status: "Expired", date: "08 Aug 2026", owner: "Riya Mehta", revision: 1, followUp: "—", category: "Commercial", placeOfSupply: "Gujarat — CGST + SGST", additionalCharges: 0, roundOff: 0, version: "R1" },
    { id: 6, code: "QT-MUM-26038", customer: "C-1003", project: "PRJ-103", branches: ["Mumbai"], surfaceItems: [{ id: 1, productCategory: "Decorative Paint", texture: "Brush", finish: "Brush", shade: "Sage", applicationArea: "Wall", area: 1400, thickness: "1 mm", rate: 160, optionalItems: ["Primer", "Stencil Work"], description: "Decorative paint finish", remarks: "", materialQuantity: 1470, materialCost: 147000, labourCost: 49000, wastageCost: 7350, transportationCost: 14700, otherCharges: 0, discount: 0, discountType: "percentage", lineTotal: 218050, hsn: "3208", gstRate: 18, gstAmount: 39249 }], optionalItems: [], subtotal: 218050, discount: 0, discountType: "percentage", taxableValue: 218050, gstAmount: 39249, gstRate: 18, amount: 258900, status: "Draft", date: "07 Aug 2026", owner: "Neel Joshi", revision: 0, followUp: "15 Aug 2026", category: "Retail", placeOfSupply: "Maharashtra — IGST", additionalCharges: 0, roundOff: 0, version: "R0" },
  ],
  inspections: [
    { id: 1, code: "INS-3321", activity: "Final inspection — Batch 2408", customer: "C-1001", status: "Under Review", date: "2026-08-13", notes: "Check sample panels against approved shade card.", branches: ["Ahmedabad"] },
    { id: 2, code: "INS-3319", activity: "Surface finish inspection", customer: "C-1002", status: "Approved", date: "2026-08-12", notes: "", branches: ["Ahmedabad"] },
    { id: 3, code: "INS-3316", activity: "Incoming material inspection", customer: "C-1003", status: "Open", date: "2026-08-11", notes: "Awaiting material batch.", branches: ["Mumbai"] },
    { id: 4, code: "INS-3310", activity: "Pre-dispatch inspection", customer: "C-1004", status: "Approved", date: "2026-08-09", notes: "", branches: ["Surat"] },
  ],
  documents: [
    { id: 1, code: "DOC-01", title: "Quotation Terms & Conditions", type: "Terms", version: "1.0", status: "Approved", updated: "2026-08-14", size: "48 KB" },
    { id: 2, code: "DOC-02", title: "Rate Master Policy", type: "Policy", version: "2.1", status: "Approved", updated: "2026-08-13", size: "72 KB" },
    { id: 3, code: "DOC-03", title: "Customer Communication Template", type: "Template", version: "1.2", status: "Under Review", updated: "2026-08-12", size: "25 KB" },
    { id: 4, code: "DOC-04", title: "Quality Procedure — Quotations", type: "Procedure", version: "3.0", status: "Approved", updated: "2026-08-11", size: "96 KB" },
    { id: 5, code: "DOC-05", title: "GST & Tax Terms", type: "Policy", version: "1.0", status: "Approved", updated: "2026-08-10", size: "38 KB" },
    { id: 6, code: "DOC-06", title: "Revision Control Procedure", type: "Procedure", version: "2.0", status: "Approved", updated: "2026-08-09", size: "61 KB" },
  ],
  followups: [
    { id: 1, code: "FU-1", date: "2026-08-16", quotation: "QT-AHM-26080", purpose: "Negotiation review", owner: "Riya Mehta", status: "Open", branches: ["Ahmedabad"] },
    { id: 2, code: "FU-2", date: "2026-08-18", quotation: "QT-AHM-26081", purpose: "Approval check", owner: "Riya Mehta", status: "Open", branches: ["Ahmedabad"] },
    { id: 3, code: "FU-3", date: "2026-08-19", quotation: "QT-MUM-26042", purpose: "Sent quotation follow-up", owner: "Neel Joshi", status: "Open", branches: ["Mumbai"] },
    { id: 4, code: "FU-4", date: "2026-08-22", quotation: "QT-SUR-26019", purpose: "Conversion follow-up", owner: "Mira Shah", status: "Done", branches: ["Surat"] },
    { id: 5, code: "FU-5", date: "2026-08-15", quotation: "QT-MUM-26038", purpose: "Draft review", owner: "Neel Joshi", status: "Overdue", branches: ["Mumbai"] },
  ],
  users: [
    { id: 1, code: "U-1", firstName: "Super", lastName: "Admin", email: "superadmin@example.com", mobileNo: "9800000001", password: "password", roleId: 1, branch: "All branches", firm: "", status: "Active" },
    { id: 2, code: "U-2", firstName: "System", lastName: "Admin", email: "sysadmin@example.com", mobileNo: "9800000002", password: "password", roleId: 2, branch: "All branches", firm: "", status: "Active" },
    { id: 3, code: "U-3", firstName: "Branch", lastName: "Admin", email: "ahmedabad.admin@example.com", mobileNo: "9800000003", password: "password", roleId: 4, branch: "Ahmedabad", firm: "Artelier Ahmedabad", status: "Active" },
    { id: 4, code: "U-4", firstName: "Branch", lastName: "Admin", email: "mumbai.admin@example.com", mobileNo: "9800000004", password: "password", roleId: 4, branch: "Mumbai", firm: "Artelier Mumbai", status: "Active" },
    { id: 5, code: "U-5", firstName: "Branch", lastName: "Admin", email: "surat.admin@example.com", mobileNo: "9800000005", password: "password", roleId: 4, branch: "Surat", firm: "Artelier Surat", status: "Active" },
  ],
  roles: seedRoles,
};
